const PRESET_PRIMERS: {
  region: string;
  cdna: string;
  forward: string;
}[] = [
  {
    region: "PR_SKL",
    cdna: "GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCTNNNNNNNNNNNCAGTTGCTCCTGGCTTTAATTTTACTGGTACAGTCTC",
    forward: "GCCTCCCTCGCGCCATCAGAGATGTGTATAAGAGACAGNNNNATAGACAAGGAACTGTATC",
  },
];

export default PRESET_PRIMERS;
